<?php

/**
* @var \Hiberus\Ruiz\Block\Index $block
*/
$ltsQualifications = $block->getQualifications();
$totalStudents = count($ltsQualifications);
$totalMarks = null;
?>
<h2 class="title">Students' notes</h2>
<?php if ($totalStudents == 0):?>
<p>There are no qualifications.</p>
<?php else: ?>
<ul>
    <?php foreach ($ltsQualifications as $qualification):?>
        <li><?= $qualification->getFirstName() ?> - <?= $qualification->getLastName() ?> - <?= $qualification->getMark() ?></li>
        <?php $totalMarks += $qualification->getMark(); endforeach;?>
    <li>Arithmetic mean: <?= round($totalMarks/$totalStudents, 2) ?></li>
</ul>
<p>Total number of students: <?= $totalStudents ?>.</p>

<?php endif; ?>
