<?php

/**
 * @var Index $block
 */

use Hiberus\Ruiz\Block\Index;

$ltsQualifications = $block->getQualifications();
$totalStudents = count($ltsQualifications);
$totalMarks = null;
?>
<h2 class="title">Students' notes</h2>
<?php if ($totalStudents == 0): ?>
    <p>There are no qualifications.</p>
<?php else: ?>
    <div id="list" data-mage-init='{"show_hide_list":{"option": value}}'>
        <ul>
            <?php foreach ($ltsQualifications as $qualification): ?>
                <li><?= $qualification->getFirstName() ?> - <?= $qualification->getLastName() ?>
                    - <?= $qualification->getMark() ?></li>
                <?php $totalMarks += $qualification->getMark(); endforeach; ?>
            <li>Arithmetic mean: <?= round($totalMarks / $totalStudents, 2) ?></li>
        </ul>
        <p>Total number of students: <?= $totalStudents ?>.</p>
    </div>

    <button id="show_hide_list">Show-Hide list</button>
<?php endif; ?>

<script>
    require([
        'jquery',
        'show_hide_list'
    ], function (show_hide_list) {
        show_hide_list('#show_hide_list', '#list');
    });
</script>
